### ISSUE TITLE
make the indentation consistent

### ISSUE THREAD

**Issue by aric87** [EQuimper/githubfindrepo#2]
https://github.com/EQuimper/githubfindrepo/blob/master/src/components/App.jsx#L37

**Comment by EQuimper** [comment]
I dont understand the indentation problem ? I think maybe cause the line its too long ?

**Comment by aric87** [comment]
The file moved to here: https://github.com/EQuimper/githubfindrepo/blob/master/app/src/components/App.jsx#L37 
Line 35 is tabbed in 1, line 36 is tabbed in 2, line 37-47 should be tabbed in 3. Not sure why it isn't
